services:
  advance-rag-api:
    build:
      context: .
      args:
        CACHEBUST: "force-rebuild"
    container_name: advance-rag-api
    depends_on:
      - opensearch
      - redis
    env_file:
      - docker.env
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --access-log
      --log-level info
    volumes:
      - ./database/db_files:/app/database/db_files
    ports:
      - "8000:8000"
    networks:
      - app-net
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - plugins.security.disabled=true
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - app-net
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net
    restart: always
    security_opt:
      - no-new-privileges:true

networks:
  app-net:
